---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12.19.36

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[aig_project::default]
#    verifier:
#      inspec_tests:
#        - test/smoke/default
#    attributes: